name: Build plccli

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true
      
      - name: Build with Makefile
        run: |
          make all
      
      - name: Create archives
        run: |
          cd build
          tar czf plccli-darwin-arm64.tar.gz plccli-darwin-arm64
          tar czf plccli-linux-amd64.tar.gz plccli-linux-amd64
          tar czf plccli-linux-arm64.tar.gz plccli-linux-arm64
      
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plccli-binaries
          path: build/*.tar.gz
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/plccli-darwin-arm64.tar.gz
            build/plccli-linux-amd64.tar.gz
            build/plccli-linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}